GET http://localhost:5000/users

###
GET http://localhost:5000/countries

###
GET http://localhost:5000/horoscopes

###
GET http://localhost:5000/users/1


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "test",
    "email": "fajarputra@gmail.com",
    "age": 19,
    "CountryId": "England",
    "Horoscope": "Virgo",
    "gender": "Male"

}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Fajar Putra Herianto",
    "email": "fajarph.dev@gmail.com",
    "age": 19,
    "gender": "Male"

}


###
DELETE http://localhost:5000/users/3
