//Get All User
GET http://localhost:5000/users

###
//Get All Student
GET http://localhost:5000/students

//Get All Teacher
###
GET http://localhost:5000/teachers

###
GET http://localhost:5000/countries

###
GET http://localhost:5000/horoscopes

###
GET http://localhost:5000/hobbies

//Get Single User
###
GET http://localhost:5000/students/3

//Get Single Teacher
###
GET http://localhost:5000/teachers/1

//Create User
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Fajarrr",
    "email": "admin@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "admin"
}

//Create Student
###
POST http://localhost:5000/students
Content-Type: application/json

{
    "name": "Ika",
    "email": "Ika@gmail.com",
    "age": 18,
    "CountryId": 3,
    "HoroscopeId": 2,
    "HobbyId": 4,
    "gender": "Female"
    
}

//Create Teacher
###
POST http://localhost:5000/teachers
Content-Type: application/json

{
    "name": "Bu Wulan",
    "email": "Wulan@gmail.com",
    "age": 38,
    "CountryId": 5,
    "HoroscopeId": 1,
    "HobbyId": 3,
    "course": "Bahasa Indonesia",
    "gender": "Female"
    
}


//Update User
###
PATCH http://localhost:5000/users/6bee2b7d-23b3-4d53-9663-85b620e73f22
Content-Type: application/json

{
    "name": "John Doe Bro Updated",
    "email": "John@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

//Update Student
###
PATCH http://localhost:5000/students/4
Content-Type: application/json

{
    "name": "Ika Amelia",
    "email": "IkaAmelia@gmail.com",
    "age": 18,
    "CountryId": 1,
    "HoroscopeId": 3,
    "HobbyId": 5,
    "gender": "Female"
}

//Update Teacher
###
PATCH http://localhost:5000/teachers/6
Content-Type: application/json

{
    "name": "Bu Wulan",
    "email": "Wulan@gmail.com",
    "age": 40,
    "CountryId": 4,
    "HoroscopeId": 2,
    "HobbyId": 5,
    "course": "MTK",
    "gender": "Female"
}

###
//Cek Akun
GET http://localhost:5000/me

###
//Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}


###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "John@gmail.com",
    "password": "12345678"
}



//Delete User
###
DELETE http://localhost:5000/users/56df1df0-3399-4e5e-b6e9-475e5b779596

//Delete Student
###
DELETE http://localhost:5000/students/3

//Delete Teacher
###
DELETE http://localhost:5000/teachers/2

###
DELETE http://localhost:5000/logout
